version: "3"

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
       
    ports:
      - "9001:9000"
    volumes:
      - ./src:/code

    networks:
      - laravel

  mysql: 
    image: mysql:8.0.31
     
    container_name: webdev-mysql 
    restart: unless-stopped 
    ports:
      - "3306:3306" 
    volumes:
      - ./docker/mysql:/var/lib/mysql 
    networks:
      - laravel 
    environment:
      MYSQL_DATABASE: midtrans-project
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql 

  nginx: 
    image: nginx:1.22.0-alpine
    ports:
      - "8083:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel  
